### ISSUE TITLE
lassondesat.github.io: Google Maps API broken

### ISSUE THREAD

**Issue by vwchu** [lassondesat/thecommons#1]
**Name** (required): lassondesat.github.io

**I'm submitting a ...**  (check one with "x")

- [x] bug report => search GitHub for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request (question)

**Current behavior**

Google Maps display is broken. Not displaying.

**Expected behavior**

Should show map with location marker.

**Reproduction of the problem**

Go to lassat.ca in your browser

**Please tell us about your environment:**

All browsers

**Comment by TheJeff** [comment]
Fixed it. The google maps function in main.js was using a legacy function called initialize_map when the function the api wants to use is called initMap. Literally a naming convention broke it.
